### PR TITLE
[docker] Add metadata for VS Code image

### LINKED ISSUE #3: [docker] Add metadata for VS Code image
Is necessary add vscode images into this repo in order to generate all repo-info metadata of Skycoin docker images.

### PR DESCRIPTION
**Pull request by stdevYuniers**
Fixes #3

Changes:

- Added to `repo-list.txt` information about folder and images to analyze by `updateit.sh` script
- Created folder `repos/dev-vscode` to storage `skycoin/skycoindev-vscode` repo info

### CODE REVIEW

**Comment by stdevPavelmc** [comment]
Please check that the remote part of both images are empty, no relevant content in there.

Try to run it online and if still fails try to run it by hand for one of them at a time, like this example:

```sh
cd  repos/dev-vscode/
../../drib.sh skycoin/skycoindev-vscode:dind
```
If still fails please contact me for revision of the scripts; maybe you found a bug.

**Comment by yuniers** [comment]
@stdevPavelmc Sorry for delay.

> Please check that the remote part of both images are empty, no relevant content in there.

On 4b8a212 it was fixed. VS Code docker images are published on Docker Hub and generate repo info for it is more easy now.

**Comment by stdevPavelmc** [comment]
@stdevYuniers Please make a ```git fetch upstream``` and then push it to resolve conflicts created by the last merge of the PR #5, all looks good to merge.

Cheers.

**Comment by olemis** [comment]
@stdevYuniers conflicts in this PR . Will be merged shortly after VS Code image will get to `develop` branch .

**Comment by stdevYuniers** [comment]
@stdevPavelmc Resolved on 2600598.
I put vscode docker image repos at end of `repos-list.txt` file.

**Pull request merged**
